os: linux
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
  - npm install -g danger@alpha

script:
  # - swift test
  - swift build
  - swiftenv install https://swift.org/builds/swift-4.0-branch/ubuntu1610/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-03-a/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-03-a-ubuntu16.10.tar.gz
  - swiftenv local 4.0-DEVELOPMENT-SNAPSHOT-2017-09-03-a
  - ./.build/debug/Marathon install danger/danger-swift --verbose
  - danger process danger-swift
